#pragma config(Motor,  port1,           frontright,    tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           frontleft,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           backdrive,     tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{

void setAll(int val) {
	motor[backdrive] = val;
	motor[frontleft] = val;
	motor[frontright] = val;
}

void driveForward(int time) {
	setAll(127);
	wait1MSec[time];
	setAll(0);
}

void turnR(int time) {
	motor[frontright] = 127;
	motor[frontleft] = -127;

	wait1Msec[time];
	setAll[0];
}

void turnL(int time) {
	motor[frontright] = -127;
	motor[frontleft] = 127;

	wait1Msec[time];
	setAll[0];
}



}
