#pragma config(Motor,  port1,           frontright,    tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           frontleft,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           backdrive,     tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{



}
